source 'https://rubygems.org'

ruby '3.4.4'

gem 'sinatra', '~> 4.0'
gem 'rack', '~> 3.0'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4'
gem 'pg', '~> 1.5'
gem 'bcrypt', '~> 3.1'
gem 'rack-cors', '~> 2.0'
gem 'json', '~> 2.7'

group :development do
  gem 'rerun', '~> 0.14'
end